server:
  port: 8002
spring:
  application:
    name: AIGOU-PRODUCT
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manythings_user?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 123
mybatis-plus:
  mapper-locations: classpath:com/manythings/products/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: com.manythings.domain,com.manythings.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true