server:
  port: 8003
  max-http-header-size: 4048576 #Request header is too large异常解决
spring:
  application:
    name: COMMON-PRIVODER
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
eureka:
  instance:
    hostname: localhsot
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/